apiVersion: "0.1"
gitVersion:
  commitSha: 6652ed6bc63437a553c3faa6e405cd66c6fd2730
  refSpec: healthz
kind: ksonnet.io/registry
libraries:
  argo:
    path: argo
    version: master
  core:
    path: core
    version: master
  tf-job:
    path: tf-job
    version: master
  tf-serving:
    path: tf-serving
    version: master
  seldon:
    path: seldon
    version: master
