apiVersion: 0.0.1
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: 0cc054047fc3590d49a517d90ea93594c44d3a0f
      refSpec: master
    name: core
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: 0cc054047fc3590d49a517d90ea93594c44d3a0f
      refSpec: master
    name: tf-job
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: 0cc054047fc3590d49a517d90ea93594c44d3a0f
      refSpec: master
    name: tf-serving
    registry: kubeflow
name: my-kubeflow
registries:
  incubator:
    gitVersion:
      commitSha: 422d521c05aa905df949868143b26445f5e4eda5
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: 6652ed6bc63437a553c3faa6e405cd66c6fd2730
      refSpec: healthz
    protocol: github
    uri: github.com/ankushagarwal/kubeflow/tree/healthz/kubeflow
version: 0.0.1
