apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://35.184.183.224
    k8sVersion: v1.7.0
    path: default
  kubeflow-dev:
    destination:
      namespace: agwl-experimental
      server: https://35.184.183.224
    k8sVersion: v1.7.0
    path: kubeflow-dev
  kubeflow-seldon:
    destination:
      namespace: kubeflow-seldon
      server: https://35.202.23.215
    k8sVersion: v1.7.0
    path: kubeflow-seldon
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: 0cc054047fc3590d49a517d90ea93594c44d3a0f
      refSpec: master
    name: core
    registry: kubeflow
  seldon:
    gitVersion:
      commitSha: 6702151e802cec0c0ed09bfb686f5e82fd37355e
      refSpec: master
    name: seldon
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: 0cc054047fc3590d49a517d90ea93594c44d3a0f
      refSpec: master
    name: tf-job
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: 0cc054047fc3590d49a517d90ea93594c44d3a0f
      refSpec: master
    name: tf-serving
    registry: kubeflow
name: my-kubeflow
registries:
  incubator:
    gitVersion:
      commitSha: 422d521c05aa905df949868143b26445f5e4eda5
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: 6702151e802cec0c0ed09bfb686f5e82fd37355e
      refSpec: master
    protocol: github
    uri: github.com/ankushagarwal/kubeflow/tree/master/kubeflow
version: 0.0.1
