apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dev-kubeflow-org
  namespace: kubeflow
spec:
  secretName: dev-kubeflow-org-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dev.kubeflow.org
  dnsNames:
  - dev.kubeflow.org
  acme:
    config:
    - http01:
        ingress: envoy-ingress
      domains:
      - dev.kubeflow.org
